version: 2

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go

branches:
  - name: main
  - name: 2.x

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-test-helpers/v3
    description: documentation
