version: 2

jobs:
  - docker:
      image: golang:1.14-buster
    template:
      name: go
    env:
      LD_RELEASE_GO_IMPORT_PATH: github.com/launchdarkly/go-test-helpers

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-test-helpers
    description: documentation
